name: Build and Calculate Hash

on:
  push:
    branches:
      - main
      - hash/*

jobs:
  build-and-hash:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: .
    outputs:
      artifact_hash: ${{ steps.generate-hash.outputs.artifact_hash }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Calculate hash
        id: generate-hash
        run: |
          DIST_HASH_OUTPUT=$(find ./dist -type f -print0 | sort --zero-terminated | \
          xargs -0 sha256sum | cut -d ' ' -f 1 | sha256sum | cut -d ' ' -f 1 | \
          sha256sum | cut -d ' ' -f 1)
          echo "artifact_hash=$DIST_HASH_OUTPUT" >> $GITHUB_OUTPUT
          echo "$DIST_HASH_OUTPUT" >> ./build_hash.txt

      - name: Cache hash
        if: github.ref == 'refs/heads/main'
        id: cache-build-hash
        uses: actions/cache@v4
        with:
          path: ./build_hash.txt
          key: ${{ runner.os }}-build-hash-${{ hashFiles('./build_hash.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-hash-

      - name: Restore hash
        if: startsWith(github.ref, 'refs/heads/hash/')
        id: restore-build-hash
        uses: actions/cache/restore@v4
        with:
          path: ./build_hash_restore.txt
          key: ${{ runner.os }}-build-hash-${{ hashFiles('./build_hash.txt') }}

      - name: Read artifact and compare hashes
        if: startsWith(github.ref, 'refs/heads/hash/')
        run: |
          CURRENT_HASH=$(shasum build_hash.txt | cut -d' ' -f1)
          RESTORED_HASH=$(shasum build_hash_restore.txt | cut -d' ' -f1)
          if [ "$CURRENT_HASH" == "$CACHED_HASH" ]; then
            echo "Hashes match: true"
          else
            echo "Hashes match: false"
          fi
